### ISSUE TITLE
sha256 argument missing

### ISSUE THREAD

**Issue by vivrii** [bandithedoge/devkitNix#3]
I tried to make a flake based on the example but ran into this issue on the latest commit which renames "sha256" to "hash":

error: function 'anonymous lambda' called without required argument 'sha256'

**Comment by bandithedoge** [comment]
The `dockerTools.pullImage` function was changed to accept a `hash` parameter last week: https://github.com/NixOS/nixpkgs/commit/d0e6b0e170391f072f0b2b45b536e48edaa387fb.

I've fixed the CI not commiting flake updates. It should work if you update your flake now.

**Comment by vivrii** [comment]
oh thanks yeah it is working now.

I'm not sure if this is an actual issue or I'm missing something as I'm pretty new to nix, but I couldn't get compilation to work without adding `export PATH="${pkgs.devkitNix.devkitARM}/opt/devkitpro/devkitARM/bin:$PATH"` to my flake.nix

**Comment by bandithedoge** [comment]
> oh thanks yeah it is working now.
> 
> I'm not sure if this is an actual issue or I'm missing something as I'm pretty new to nix, but I couldn't get compilation to work without adding `export PATH="${pkgs.devkitNix.devkitARM}/opt/devkitpro/devkitARM/bin:$PATH"` to my flake.nix

See https://github.com/bandithedoge/devkitNix/commit/ff9fcdb08b1d0cb497125fb887d094d9773d136f
